### ISSUE TITLE
Ability to tag a show on add

### ISSUE THREAD

**Issue by notmayo** [christophercatt/listarr#2]
Heyo, sorry if this is the wrong way to request a feature; is it possible to be able to add a tag to a list? Radarr has this functionality and it helps to track where/why something was added.

**Comment by christophercatt** [comment]
Hi @notmayo 

Yes this is a perfect way to request a feature! Tags are currently planned for implementation and is viewable at the now public Trello board, found here: https://trello.com/b/sLWoaEgx

I will mark this issue as closed for now as the feature will be worked on soon! I will be adding the Trello link to the project README, so you can check back on there to see the progress of it.
