### ISSUE TITLE
[feature request] add reverse proxy compatibility with url base

### ISSUE THREAD

**Issue by manuelbraeuer** [christophercatt/listarr#3]
hi,

i would appreciate if you could if you can add an url base like it is done in sonarr/radarr. it would be much easier to deploy listarr via reverse proxy like apache or nginx.

manuel

**Comment by christophercatt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [URL Base](https://trello.com/c/EHlddIdE/58-url-base)

**Comment by christophercatt** [comment]
Hi, 

I have added this to the 'Feature Request' section on the road-map linked in the previous comment. You can track the status and progress of the feature request on there.

I will close this issue for now and update you when there is progress. Currently I am working on a couple of feature updates before tackling additional feature requests (also on the board linked above), so it could be 1-2 weeks before this is fully looked into.

Many thanks
